# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zgedit.ui'
#
# Created: Mon Sep 17 21:21:50 2007
#      by: PyQt4 UI code generator 4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(QtCore.QSize(QtCore.QRect(0,0,726,392).size()).expandedTo(MainWindow.minimumSizeHint()))

        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")

        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")

        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")

        self.hboxlayout1 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout1.setSpacing(3)
        self.hboxlayout1.setMargin(3)
        self.hboxlayout1.setObjectName("hboxlayout1")

        self.comboBox_class = QtGui.QComboBox(self.groupBox)
        self.comboBox_class.setMinimumSize(QtCore.QSize(50,0))
        self.comboBox_class.setObjectName("comboBox_class")
        self.hboxlayout1.addWidget(self.comboBox_class)
        self.hboxlayout.addWidget(self.groupBox)

        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")

        self.hboxlayout2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.hboxlayout2.setSpacing(3)
        self.hboxlayout2.setMargin(3)
        self.hboxlayout2.setObjectName("hboxlayout2")

        self.comboBox_subject = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_subject.setMinimumSize(QtCore.QSize(250,0))
        self.comboBox_subject.setObjectName("comboBox_subject")
        self.hboxlayout2.addWidget(self.comboBox_subject)
        self.hboxlayout.addWidget(self.groupBox_2)

        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")

        self.hboxlayout3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.hboxlayout3.setSpacing(3)
        self.hboxlayout3.setMargin(3)
        self.hboxlayout3.setObjectName("hboxlayout3")

        self.comboBox_pupil = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_pupil.setMinimumSize(QtCore.QSize(250,0))
        self.comboBox_pupil.setObjectName("comboBox_pupil")
        self.hboxlayout3.addWidget(self.comboBox_pupil)

        self.pushButton_previous = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_previous.setIcon(QtGui.QIcon("icons/go-back.png"))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.hboxlayout3.addWidget(self.pushButton_previous)

        self.pushButton_next = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_next.setIcon(QtGui.QIcon("icons/go-forward.png"))
        self.pushButton_next.setObjectName("pushButton_next")
        self.hboxlayout3.addWidget(self.pushButton_next)
        self.hboxlayout.addWidget(self.groupBox_3)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vboxlayout.addWidget(self.line)

        self.graphicsView = GView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.vboxlayout.addWidget(self.graphicsView)

        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setObjectName("hboxlayout4")

        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.hboxlayout4.addWidget(self.label)

        self.lineEdit_teacher = QtGui.QLineEdit(self.centralwidget)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_teacher.sizePolicy().hasHeightForWidth())
        self.lineEdit_teacher.setSizePolicy(sizePolicy)
        self.lineEdit_teacher.setFrame(False)
        self.lineEdit_teacher.setReadOnly(True)
        self.lineEdit_teacher.setObjectName("lineEdit_teacher")
        self.hboxlayout4.addWidget(self.lineEdit_teacher)

        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem)

        self.frame_chars = QtGui.QFrame(self.centralwidget)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_chars.sizePolicy().hasHeightForWidth())
        self.frame_chars.setSizePolicy(sizePolicy)
        self.frame_chars.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_chars.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_chars.setObjectName("frame_chars")
        self.hboxlayout4.addWidget(self.frame_chars)
        self.vboxlayout.addLayout(self.hboxlayout4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,726,28))
        self.menubar.setObjectName("menubar")

        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")

        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")

        self.menu_Report = QtGui.QMenu(self.menubar)
        self.menu_Report.setObjectName("menu_Report")
        MainWindow.setMenuBar(self.menubar)

        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(self.toolBar)

        self.action_Copy = QtGui.QAction(MainWindow)
        self.action_Copy.setIcon(QtGui.QIcon("icons/copy.png"))
        self.action_Copy.setObjectName("action_Copy")

        self.action_Cut = QtGui.QAction(MainWindow)
        self.action_Cut.setIcon(QtGui.QIcon("icons/cut.png"))
        self.action_Cut.setObjectName("action_Cut")

        self.action_Paste = QtGui.QAction(MainWindow)
        self.action_Paste.setIcon(QtGui.QIcon("icons/paste.png"))
        self.action_Paste.setObjectName("action_Paste")

        self.action_Undo = QtGui.QAction(MainWindow)
        self.action_Undo.setIcon(QtGui.QIcon("icons/undo.png"))
        self.action_Undo.setObjectName("action_Undo")

        self.action_Redo = QtGui.QAction(MainWindow)
        self.action_Redo.setIcon(QtGui.QIcon("icons/redo.png"))
        self.action_Redo.setObjectName("action_Redo")

        self.action_styleS = QtGui.QAction(MainWindow)
        self.action_styleS.setCheckable(True)
        self.action_styleS.setIcon(QtGui.QIcon("icons/styleS.png"))
        self.action_styleS.setObjectName("action_styleS")

        self.action_styleN = QtGui.QAction(MainWindow)
        self.action_styleN.setCheckable(True)
        self.action_styleN.setChecked(True)
        self.action_styleN.setIcon(QtGui.QIcon("icons/styleN.png"))
        self.action_styleN.setObjectName("action_styleN")

        self.action_styleSR = QtGui.QAction(MainWindow)
        self.action_styleSR.setCheckable(True)
        self.action_styleSR.setIcon(QtGui.QIcon("icons/styleSR.png"))
        self.action_styleSR.setObjectName("action_styleSR")

        self.action_indent = QtGui.QAction(MainWindow)
        self.action_indent.setIcon(QtGui.QIcon("icons/indent.png"))
        self.action_indent.setObjectName("action_indent")

        self.action_unindent = QtGui.QAction(MainWindow)
        self.action_unindent.setIcon(QtGui.QIcon("icons/unindent.png"))
        self.action_unindent.setObjectName("action_unindent")

        self.action_Print = QtGui.QAction(MainWindow)
        self.action_Print.setIcon(QtGui.QIcon("icons/print.png"))
        self.action_Print.setObjectName("action_Print")

        self.action_RequestCheck = QtGui.QAction(MainWindow)
        self.action_RequestCheck.setCheckable(True)
        self.action_RequestCheck.setIcon(QtGui.QIcon("icons/finished.png"))
        self.action_RequestCheck.setObjectName("action_RequestCheck")

        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setIcon(QtGui.QIcon("icons/open.png"))
        self.action_Open.setObjectName("action_Open")

        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setIcon(QtGui.QIcon("icons/quit.png"))
        self.action_Quit.setObjectName("action_Quit")

        self.action_nextUnfinished = QtGui.QAction(MainWindow)
        self.action_nextUnfinished.setIcon(QtGui.QIcon("icons/nextUnfinished.png"))
        self.action_nextUnfinished.setObjectName("action_nextUnfinished")

        self.action_autospellcheck = QtGui.QAction(MainWindow)
        self.action_autospellcheck.setCheckable(True)
        self.action_autospellcheck.setIcon(QtGui.QIcon("icons/autospellcheck.png"))
        self.action_autospellcheck.setObjectName("action_autospellcheck")

        self.action_checkSpelling = QtGui.QAction(MainWindow)
        self.action_checkSpelling.setIcon(QtGui.QIcon("icons/spellcheck.png"))
        self.action_checkSpelling.setObjectName("action_checkSpelling")

        self.action_Print1 = QtGui.QAction(MainWindow)
        self.action_Print1.setIcon(QtGui.QIcon("icons/print1.png"))
        self.action_Print1.setObjectName("action_Print1")

        self.action_Synchronize = QtGui.QAction(MainWindow)
        self.action_Synchronize.setIcon(QtGui.QIcon("icons/refresh.png"))
        self.action_Synchronize.setObjectName("action_Synchronize")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Synchronize)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menu_Report.addAction(self.action_RequestCheck)
        self.menu_Report.addAction(self.action_Print)
        self.menu_Report.addSeparator()
        self.menu_Report.addAction(self.action_nextUnfinished)
        self.menu_Report.addSeparator()
        self.menu_Report.addAction(self.action_autospellcheck)
        self.menu_Report.addAction(self.action_checkSpelling)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Report.menuAction())
        self.toolBar.addAction(self.action_Copy)
        self.toolBar.addAction(self.action_Cut)
        self.toolBar.addAction(self.action_Paste)
        self.toolBar.addAction(self.action_Undo)
        self.toolBar.addAction(self.action_Redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_styleN)
        self.toolBar.addAction(self.action_styleS)
        self.toolBar.addAction(self.action_styleSR)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_indent)
        self.toolBar.addAction(self.action_unindent)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Print1)
        self.toolBar.addAction(self.action_Print)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_RequestCheck)
        self.toolBar.addAction(self.action_nextUnfinished)
        self.toolBar.addAction(self.action_checkSpelling)
        self.toolBar.addAction(self.action_autospellcheck)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Quit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit,QtCore.SIGNAL("triggered()"),MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_("MainWindow"))
        self.groupBox.setTitle(_("Class"))
        self.groupBox_2.setTitle(_("Subject"))
        self.groupBox_3.setTitle(_("Pupil"))
        self.pushButton_previous.setToolTip(_("Previous pupil"))
        self.pushButton_next.setToolTip(_("Next pupil"))
        self.label.setText(_("Teacher:"))
        self.frame_chars.setToolTip(_("Click on a character to insert it in the text"))
        self.menu_File.setTitle(_("&File"))
        self.menu_Edit.setTitle(_("&Edit"))
        self.menu_Report.setTitle(_("&Report"))
        self.action_Copy.setText(_("&Copy"))
        self.action_Copy.setToolTip(_("Copy marked text"))
        self.action_Copy.setShortcut(_("Ctrl+C"))
        self.action_Cut.setText(_("Cu&t"))
        self.action_Cut.setToolTip(_("Cut marked text"))
        self.action_Cut.setShortcut(_("Ctrl+X"))
        self.action_Paste.setText(_("&Paste"))
        self.action_Paste.setToolTip(_("Paste to cursor position"))
        self.action_Paste.setShortcut(_("Ctrl+V"))
        self.action_Undo.setText(_("&Undo"))
        self.action_Undo.setToolTip(_("Undo last editing operation(s)"))
        self.action_Redo.setText(_("&Redo"))
        self.action_Redo.setToolTip(_("Redo last undone editing operation"))
        self.action_styleS.setText(_("Special style text"))
        self.action_styleN.setText(_("Normal style text"))
        self.action_styleSR.setText(_("Special style text (right aligned)"))
        self.action_indent.setText(_("indent"))
        self.action_indent.setToolTip(_("Increase line indentation"))
        self.action_unindent.setText(_("unindent"))
        self.action_unindent.setToolTip(_("Decrease line indentation"))
        self.action_Print.setText(_("Print"))
        self.action_Print.setToolTip(_("Print all reports for this subject"))
        self.action_Print.setShortcut(_("Ctrl+P"))
        self.action_RequestCheck.setText(_("Report completed"))
        self.action_RequestCheck.setToolTip(_("Report completed"))
        self.action_Open.setText(_("&Open"))
        self.action_Open.setToolTip(_("Open Report Database"))
        self.action_Open.setShortcut(_("Ctrl+O"))
        self.action_Quit.setText(_("&Quit"))
        self.action_Quit.setShortcut(_("Ctrl+Q"))
        self.action_nextUnfinished.setText(_("Next unfinished report"))
        self.action_nextUnfinished.setToolTip(_("Go to next uncompleted report"))
        self.action_autospellcheck.setText(_("Auto-spellcheck"))
        self.action_autospellcheck.setToolTip(_("Automatic spellchecking"))
        self.action_checkSpelling.setText(_("Check spelling"))
        self.action_checkSpelling.setIconText(_("Check spelling"))
        self.action_checkSpelling.setToolTip(_("Interactive spelling checker"))
        self.action_Print1.setText(_("Print this report"))
        self.action_Print1.setToolTip(_("Print just this report"))
        self.action_Synchronize.setText(_("Synchronize"))

from guiCanvas import GView
