#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2007 Michael Towers

# This file is part of Zeugs.
#
# Zeugs is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# Zeugs is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Zeugs; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#

# gettextify

# Modify a file outputted by pyuic4 to work with gettext rather than
# QLinguist.

import re
rem = re.compile('\\QtGui.QApplication.translate\\([^,]*, "(.*)",.*')

def gettextify(filepath):
    file = open(filepath)
    lines = []
    for line in file:
#        m = rem.search(line)
#        if m:
#            print m.groups()
        lines.append(rem.sub('_("\\1"))', line))
    file.close()
    file = open(filepath, "wb")
    for ln in lines:
        file.write(ln)
    file.close()

if __name__ == "__main__":
    import sys
    gettextify(sys.argv[1])
